BookSpade/BookSpade.Revamped/Models/TransactionComment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BookSpade.Revamped.Models
{
   

    public class TransactionComment
    {
        public int CommentId { get; set; }
        public string Comment { get; set; }
        public int TransactionId { get; set; }
        public ActionBy ActionBy { get; set; }
        public TransactionDetailModel Details { get; set; } 

        public TransactionComment(int commentId, string comment, ActionBy actionBy, Transaction transaction)
        {
            CommentId = commentId;
            Comment = comment;
            TransactionId = transaction.TransactionId;
            Details = new TransactionDetailModel(transaction); 
        }
    }
}

BookSpade/BookSpade.Revamped/Controllers/TransactionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using BookSpade.Revamped.Handlers;
using BookSpade.Revamped.Models;
using BookSpade.Revamped.Utilities;

namespace BookSpade.Revamped.Controllers
{
    public class TransactionController : Controller
    {
        //
        // GET: /Transaction/

        #region Index

        public ActionResult Index()
        {
            return View();
        }

        #endregion

        #region TransactionHistory

        public ActionResult TransactionHistory()
        {
            string username = User.Identity.Name;
            Profile profile = ProfileHandler.GetProfile(username);
            IEnumerable<Transaction> transactions = TransactionHandler.getUserTransactionHistory(profile.ProfileId);

            IEnumerable<TransactionDetailModel> detailedHistory = transactions.Select(
                x => new TransactionDetailModel(x));

            return View(detailedHistory); 
        }

        #endregion

        #region TransactionDetails

        public ActionResult TransactionDetails(int transactionId)
        {
            Transaction transaction = TransactionHandler.getTransaction(transactionId);

            Profile buyer = ProfileHandler.GetProfile(transaction.BuyerId);
            Profile seller = ProfileHandler.GetProfile(transaction.SellerId);
            if (User.Identity.Name == buyer.Email)
            {
                transaction.CurrentUser = ActionBy.Buyer;
                transaction.CounterPartyName = seller.Name;
            }
            else
            {
                transaction.CurrentUser = ActionBy.Seller;
                transaction.CounterPartyName = buyer.Name;
            }

            if ((transaction.CurrentUser == ActionBy.Buyer && transaction.Confirmed == Confirmed.ByBuyer)
                || (transaction.CurrentUser == ActionBy.Seller && transaction.Confirmed == Confirmed.BySeller))
            {
                transaction.ConfirmedByCurrentUser = true;
            }
            else
            {
                transaction.ConfirmedByCurrentUser = false;
            }

            TransactionCommentModel model = new TransactionCommentModel(transaction, User.Identity.Name);
            return View(model);
        }

        #endregion

        #region newComment

        public JsonResult newComment(string comment, ActionBy commentor, int userId, int OtherUserId, int transactionId)
        {
            Comment newComment = new Comment(
                -1,
                comment,
                userId,
                commentor,
                transactionId,
                1,
                0,
                DateTime.Now,
                DateTime.Now
            ); 
            CommentHandler.createComment(newComment);

            return Json("");
        }

        #endregion

        #region ConfirmTransaction

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ConfirmTransaction(Transaction transaction)
        {
            if (ModelState.IsValid)
            {
                TransactionHandler.ConfirmTransaction(transaction);
            }

            return RedirectToAction("Index", "Home");
        }

        #endregion

        #region CancelTransaction

        [HttpPost]
        public ActionResult CancelTransaction(Transaction transaction)
        {
            if (ModelState.IsValid)
            {
                TransactionHandler.CancelTransaction(transaction);
            }

            return RedirectToAction("Index", "Home");
        }

        #endregion

        

    }
}

BookSpade/BookSpade.Revamped/Views/Transaction/Partial Views/_TransactionActions.cshtml
@model Transaction

@if (Model.IsActive == 1 && Model.IsDeleted == 0 && !Model.ConfirmedByCurrentUser)
{
  <div class="transactionAction">
    @using (Html.BeginForm("ConfirmTransaction", "Transaction", FormMethod.Post, new { id = "confirmTransactionForm" }))
    {
      <div>
        <button id="confirmTransaction" type="button" class="green-button">
          Confirm Transaction
        </button>
      </div>
   
      @Html.HiddenFor(x => x.TransactionId);
      @Html.HiddenFor(x => x.SellerId);
      @Html.HiddenFor(x => x.SellerPostId);
      @Html.HiddenFor(x => x.BuyerId);
      @Html.HiddenFor(x => x.BuyerPostId);
      @Html.HiddenFor(x => x.FinalPrice);
      
      @Html.HiddenFor(x => x.CurrentUser);
    }
  </div>

  <div class="transactionAction">
    @using (Html.BeginForm("CancelTransaction", "Transaction", FormMethod.Post, new { id = "cancelTransactionForm" }))
    {
      <div>
        <button id="cancelTransaction" type="button" class="red-button">
          Cancel Transaction
        </button>
      </div>
   
      @Html.HiddenFor(x => x.TransactionId);
      @Html.HiddenFor(x => x.SellerId);
      @Html.HiddenFor(x => x.SellerPostId);
      @Html.HiddenFor(x => x.BuyerId);
      @Html.HiddenFor(x => x.BuyerPostId);

      @Html.HiddenFor(x => x.CurrentUser);
    }
  </div>

  <div id="confirmationWarning">
    @if (@Model.DaysRemaining == 1)
    {
      <span>This transaction will be automatically confirmed tomorrow.</span>
    }
    else
    {
      <span>This transaction will be automatically confirmed in @Model.DaysRemaining days.</span>
    }
  </div>

  <!-- Confirm Transaction Modal -->
  <div id="confirmationModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <div class="modal-body">
      We hope your transaction went smoothly!
      <br />
      Please let us know of the final price you traded at.

      <div class="control-group">
        <label class="control-label" for="confirmFinalPrice">Final price</label>
        <div class="input-prepend">
          <span class="add-on">$</span>
          @if (Model.FinalPrice != null)
          {
            <input class="input-medium" id="confirmFinalPrice" name="confirmFinalPrice" type="text"
              value="@Model.FinalPrice">
          }
          else
          {
            <input class="input-medium" id="confirmFinalPrice" name="confirmFinalPrice" type="text"
              value="@Model.InitialPrice">
          }
        </div>
      </div>
    </div>
    <div class="modal-footer">
      <button class="grey-button" data-dismiss="modal" aria-hidden="true">Back</button>
      <button id="proceedConfirmTransaction" class="green-button">Confirm Transaction</button>
    </div>
  </div>

  <!-- Cancel Transaction Modal -->
  <div id="cancellationModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <div class="modal-body">
      <b>WARNING!! </b>
      You will be matched with someone else for this book.
    </div>
    <div class="modal-footer">
      <button class="grey-button" data-dismiss="modal" aria-hidden="true">Back</button>
      <button id="proceedCancelTransaction" class="red-button">Cancel Transaction</button>
    </div>
  </div>
}
else if (Model.IsActive == 1 && Model.IsDeleted == 0)
{
  <div>You've already confirmed this transaction.<br />Please wait for @Model.CounterPartyName to confirm so we can close the transaction.</div>
}
else if (Model.IsActive == 0)
{
  <button id="completedButton" class="green-button" disabled>Transaction Completed</button>
}
else if (Model.IsDeleted == 1)
{
  <button id="cancelledButton" class="red-button" disabled>Transaction Cancelled</button>
}

BookSpade/BookSpade.Revamped/Views/Transaction/Partial Views/_TransactionComment.cshtml
@model Comment

@{

  if (Model.CommentByCurrentUser)
  {
    <li class="user-comment">
      <div class="user-bubble">
          <span>@Model.comment</span>
      </div>
    </li>
  }
  else
  {
    <li class="counterparty-comment">
      <div class="counterparty-bubble">       
        <span>@Model.comment</span>
      </div>
    </li>
  }
}

BookSpade/BookSpade.Revamped/Views/Transaction/Partial Views/_TransactionHistoryDetail.cshtml
@model TransactionDetailModel

<li> 
  <div class="item-container">
    <h4 class="item-title">
      @Model.BookTitle
    </h4>
    <div>
      <div class="isbn-course">
        <div class="BookDetail lbl">ISBN : </div><div class="BookDetail">@Model.ISBN</div>
        <div class="BookDetail lbl">Course : </div><div class="BookDetail">@Model.CourseName</div>
      </div>
      <div class="prices">
        <div class="BookDetail lbl">Initial Price : </div><div class="BookDetail">@Model.Price</div>
        @{
          if (Model.FinalPrice != null){
            <div class="BookDetail lbl">
              Final Price : 
            </div>
            <div class="BookDetail">
              Model.FinalPrice
            </div>
          } else {
            <div class="BookDetail lbl">
              Final Price : 
            </div>
            <div class="BookDetail">
              To be determined
            </div>
          }
        }
      </div>
    </div>
  </div>
</li>

BookSpade/BookSpade.Revamped/Views/Transaction/Partial Views/_TransactionHistoryItem.cshtml
@model TransactionDetailModel

<li data-id="@(Model.transaction.TransactionId)">
  <div class="item-container">
    <div class="item-title One-line Truncate" title="@Model.BookTitle">@Model.BookTitle</div>
    <div class="item-info">@Model.ISBN</div>
    <div class="item-info">@Model.CourseName</div>
    <div class="item-info">@Model.Price</div>

    @if (Model.transaction.IsActive == 1 && Model.transaction.IsDeleted == 0)
    {
      <div class="item-info t-pending">
        Pending
      </div>
    }
    else if (Model.transaction.IsActive == 0)
    {
      <div class="item-info t-complete">
        Complete
      </div>
    }
    else if (Model.transaction.IsDeleted == 1)
    {
      <div class="item-info t-cancelled">
        Cancelled
      </div>
    }

  </div>
</li>