BookSpade/BookSpade.Revamped/Models/TransactionHistory.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BookSpade.Revamped.Models
{
    public class TransactionHistory
    {
        public int TransactionHistoryId { get; set; }
        public int ProfileId { get; set; }
        public Profile Profile { get; set; } 
        public IEnumerable<TransactionDetailModel> TransactionModels { get; set; }

        public TransactionHistory(int transactionHistoryId, int profileId, IEnumerable<TransactionDetailModel> transactionModels)
        {
            TransactionHistoryId = transactionHistoryId;
            ProfileId = profileId;
            TransactionModels = transactionModels; 
        }
    }
}

BookSpade/BookSpade.Revamped/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookSpade.Revamped.Models;
using BookSpade.Revamped.Utilities;
using BookSpade.Revamped.Handlers;
using System.Threading.Tasks;

namespace BookSpade.Revamped.Controllers
{
    public class PostController : Controller
    {
        //
        // GET: /Post/

        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /Post/Create

        [Authorize]
        public ActionResult Create(string postType)
        {
            IEnumerable<Textbook> textBookCollection = TextbookHandler.getAllTextbooks();

            // test data
            //for(int i = 0; i < 100; i++) {
            //    Textbook book = new Textbook(
            //        i,
            //        "Financial Accounting " + i,
            //        "100000000000" + i,
            //        "Author " + i,
            //        100 + i,
            //        "AFM 10" + i,
            //        null,
            //        10 + i,
            //        1,
            //        0,
            //        DateTime.Now,
            //        DateTime.Now
            //    );
            //    textBookCollection.Add(book);
            //}
            //

            var viewModel = new CreatePostModel()
            {
                ActionBy = postType == "Buy" ? ActionBy.Buyer : ActionBy.Seller,
                BookCondition = BookCondition.Excellent,
                PostTypes = SelectListUtility.getPostTypes(),
                BookConditions = SelectListUtility.getBookConditions(),
                Textbooks = textBookCollection
            };

            return View("CreatePost", viewModel);
        }

        //
        // POST: /Post/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreatePost(CreatePostModel model)
        {
            if (ModelState.IsValid)
            {
                int textbookId = model.TextBookId;

                // if we have a new textbook, store it
                if (model.IsNewBook)
                {
                    // proceed if course id exists; otherwise create the course first
                    Course course = CourseHandler.getCourseByName(model.CourseName);
                    if (course == null)
                    {
                        model.CourseId = CourseHandler.CreateCourse(model.CourseName);
                    }

                    var newTextbook = new Textbook(
                        -1, // id doesnt matter here
                        model.BookTitle,
                        model.ISBN,
                        model.Author,
                        model.CourseId,
                        model.CourseName,
                        model.BookImageUrl,
                        null,
                        1,
                        0,
                        DateTime.Now,
                        DateTime.Now
                    );

                    textbookId = TextbookHandler.createTextBook(newTextbook);
                }
                
                int profileId = ProfileHandler.GetProfileId(User.Identity.Name);
                int price = model.Price;
                ActionBy actionBy = model.ActionBy;

                if (model.IsNegotiable)
                {
                    if (actionBy == ActionBy.Buyer)
                    {
                        price = int.MaxValue;
                    }
                    else
                    {
                        price = 0;
                    }
                }

                var newPost = new Post(
                    -1, // id doesnt matter here
                    profileId,
                    textbookId,
                    actionBy,
                    price,
                    model.BookCondition,
                    0,
                    1,
                    0,
                    DateTime.Now,
                    DateTime.Now
                );

                int postId = PostHandler.createPost(newPost);
                newPost.PostId = postId;
                Task.Run(() => QueueWorker.AddPost(newPost));

                // TODO: redirect to special "you've successfully created post" page
                // with links to create another buy/sell post
                return RedirectToAction("Index", "Home");
            }

            // If we got this far, something failed, redisplay form
            IEnumerable<Textbook> textBookCollection = TextbookHandler.getAllTextbooks();

            // test data
            //for(int i = 0; i < 100; i++) {
            //    Textbook book = new Textbook(
            //        i,
            //        "Financial Accounting " + i,
            //        "100000000000" + i,
            //        "Author " + i,
            //        100 + i,
            //        "AFM 10" + i,
            //        null,
            //        10 + i,
            //        1,
            //        0,
            //        DateTime.Now,
            //        DateTime.Now
            //    );
            //    textBookCollection.Add(book);
            //}

            model.PostTypes = SelectListUtility.getPostTypes();
            model.BookConditions = SelectListUtility.getBookConditions();
            model.Textbooks = textBookCollection;

            return View("CreatePost", model);
        }
    }
}

BookSpade/BookSpade.Revamped/Controllers/TransactionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using BookSpade.Revamped.Handlers;
using BookSpade.Revamped.Models;
using BookSpade.Revamped.Utilities;

namespace BookSpade.Revamped.Controllers
{
    public class TransactionController : Controller
    {
        //
        // GET: /Transaction/

        #region Index

        public ActionResult Index()
        {
            return View();
        }

        #endregion

        #region TransactionHistory

        public ActionResult TransactionHistory()
        {
            string username = User.Identity.Name;
            Profile profile = ProfileHandler.GetProfile(username);
            IEnumerable<Transaction> transactions = TransactionHandler.getUserTransactionHistory(profile.ProfileId);

            IEnumerable<TransactionDetailModel> detailedHistory = transactions.Select(
                x => new TransactionDetailModel(x));

            return View(detailedHistory); 
        }

        #endregion

        #region TransactionDetails

        public ActionResult TransactionDetails(int transactionId)
        {
            Transaction transaction = TransactionHandler.getTransaction(transactionId);

            Profile buyer = ProfileHandler.GetProfile(transaction.BuyerId);
            Profile seller = ProfileHandler.GetProfile(transaction.SellerId);
            if (User.Identity.Name == buyer.Email)
            {
                transaction.CurrentUser = ActionBy.Buyer;
                transaction.CounterPartyName = seller.Name;
            }
            else
            {
                transaction.CurrentUser = ActionBy.Seller;
                transaction.CounterPartyName = buyer.Name;
            }

            if ((transaction.CurrentUser == ActionBy.Buyer && transaction.Confirmed == Confirmed.ByBuyer)
                || (transaction.CurrentUser == ActionBy.Seller && transaction.Confirmed == Confirmed.BySeller))
            {
                transaction.ConfirmedByCurrentUser = true;
            }
            else
            {
                transaction.ConfirmedByCurrentUser = false;
            }

            TransactionCommentModel model = new TransactionCommentModel(transaction, User.Identity.Name);
            return View(model);
        }

        #endregion

        #region newComment

        public JsonResult newComment(string comment, ActionBy commentor, int userId, int OtherUserId, int transactionId)
        {
            Comment newComment = new Comment(
                -1,
                comment,
                userId,
                commentor,
                transactionId,
                1,
                0,
                DateTime.Now,
                DateTime.Now
            ); 
            CommentHandler.createComment(newComment);

            return Json("");
        }

        #endregion

        #region ConfirmTransaction

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ConfirmTransaction(Transaction transaction)
        {
            if (ModelState.IsValid)
            {
                TransactionHandler.ConfirmTransaction(transaction);
            }

            return RedirectToAction("Index", "Home");
        }

        #endregion

        #region CancelTransaction

        [HttpPost]
        public ActionResult CancelTransaction(Transaction transaction)
        {
            if (ModelState.IsValid)
            {
                TransactionHandler.CancelTransaction(transaction);
            }

            return RedirectToAction("Index", "Home");
        }

        #endregion

        

    }
}

BookSpade/BookSpade.Revamped/Views/Transaction/TransactionDetails.cshtml
@model TransactionCommentModel

@{
    ViewBag.Title = "Transaction";
}

@Styles.Render("~/Content/font-awesome.min.css")
@Styles.Render("~/Content/Pages/TransactionDetail.css")

<div id="transactionDetailsContainer">
  <div id="transactionDetailsContent">
    <h1>My Transaction</h1>
    <div id="contentSection">
      <div class="user-info">
        @if (Model.UserFacebookId != null)
        {
          <img src="http://graph.facebook.com/@Model.UserFacebookId/picture?width=500&height=500" class="img-rounded" />
        }
        else
        {
          <img src="~/Images/default-user.jpg" />
        }

        <div class="user-info-name">
          Me
        </div>
      </div>
      <div id="transactionInfo">
        <div class="details-block">
          <div class="details-label">
            Title
          </div>
          <div class="details-value">
            @Model.Details.BookTitle
          </div>
        </div>

        <div class="details-block">
          <div class="details-label">
            Book Condition
          </div>
          <div class="details-value">
            @Model.Details.Condition
          </div>
        </div>

        <div class="details-block">
          <div class="details-label">
            Course Name
          </div>
          <div class="details-value">
            @Model.Details.CourseName
          </div>
        </div>

        <div class="details-block">
          <div class="details-label">
            ISBN
          </div>
          <div class="details-value">
            @Model.Details.ISBN
          </div>
        </div>

        <div class="details-block">
          <div class="details-label">
            BookStore Price
          </div>
          <div class="details-value">
            $@Model.Details.StorePrice
          </div>
        </div>

        <div class="details-block">
          <div class="details-label">
            Initial Offer
          </div>
          <div class="details-value">
            $@Model.Details.Price
          </div>
        </div>
      </div>
      <div class="user-info">
        @if (Model.CounterPartyFacebookId != null)
        {
          <img src="http://graph.facebook.com/@Model.CounterPartyFacebookId/picture?width=500&height=500" class="img-rounded" />
        }
        else
        {
          <img src="~/Images/default-user.jpg" />
        }

        <div class="user-info-name">
          @Model.CounterPartyDisplayName
        </div>
      </div>
    </div>
    <div id="interactionSection">
      <div id="actions">
        @Html.Partial("_TransactionActions", Model.Details.transaction)
      </div>

      <div id="comments">
        <div id="showComments">
          <div id="commentAngleLabel">Show Chat</div>
          <i id="commentAngle" class="fa fa-angle-down"></i>
        </div>
        <div id="commentArea">
          <div id="commentContainer" class="d-iblock">
            <ul id="commentList">
              @foreach (Comment comment in Model.Comments)
              {
                @Html.Partial("_TransactionComment", comment); 
              }
            </ul>
            
            @if (Model.Details.transaction.IsActive == 1 && Model.Details.transaction.IsDeleted == 0)
            {
              <textarea id="sendComment" name="NewComment" rows="1" cols="10" maxlength="225"></textarea>
              <div id="commentAction">
                <button id="submitComment" type="submit" class="blue-button comment-submit" onclick="newComment()">Send Message</button>
              </div>
            }
            else
            {
              <textarea id="sendComment" name="NewComment" rows="1" cols="10" maxlength="225" disabled></textarea>
            }

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

@section Scripts {
  @Scripts.Render("~/bundles/transactionDetails")
  <script type="text/javascript">
    function newComment() {
      var Comment = $("#sendComment").val();
      if (Comment.length == 0) {
        return;
      }

      // syntax here should match that of _TransactionComment
      $("#commentContainer ul").append(
        "<li class=\"user-comment\">" +
          "<div class=\"user-bubble\">" +
            "<span>" + Comment + "</span>" +
          "</div>" +
        "</li>"
      );

      $('#commentList').scrollTop(10000000);
      $("#sendComment").val("");
      updateCountdown();

      $.ajax({
        url: '@Url.Action("newComment", "Transaction")',
        data: {
          comment: Comment,
          commentor: "@(Model.UserAction)",
              userId: "@(Model.UserId)",
            OtherUserId: "@(Model.CounterPartyId)",
            transactionId: "@(Model.Details.transaction.TransactionId)"
          },
        type: 'POST',
        success: function (result) {
        }
      });
    }
  </script>
}

BookSpade/BookSpade.Revamped/Views/Transaction/TransactionHistory.cshtml
@model IEnumerable<TransactionDetailModel>

@Styles.Render("~/Content/effects/qtip2/jquery.qtip.min.css")
@Styles.Render("~/Content/Pages/TransactionHistory.css")

<div id="historyWrapper">
  <div id="historyContainer">
    <div id="history-header">Transaction History</div>
  
    @if(Model.Count() == 0) {
      <div id="no-trans-container">
        <div>You do not have any pending transactions.</div>
        <div class="no-trans-btn-desc">Need help getting a book or selling one you're done with?</div>
        <div id="needToBuySell">
          <div class="no-trans-btn-buysell">
            <a href="@(Url.Action("Create", "Post", new { isBuy = true }))" title="Buy Textbooks">
                <div class="buttonBuySell blue-button">Buy</div>
            </a>
          </div>
          <div class="no-trans-btn-buysell">
            <a href="@(Url.Action("Create", "Post", new { isBuy = false }))" title="Sell Textbooks">
                <div class="buttonBuySell blue-button">Sell</div>
            </a>
          </div>
        </div>
      </div>
    } else {
      <div id="list-header" class="item-container">
        <div class="item-title">Book Title</div>
        <div class="item-info">ISBN</div>
        <div class="item-info">Course</div>
        <div class="item-info">Initial Price</div>
        <div class="item-info">Status</div>
      </div>
      <ul class="user-history SearchResults wave">
        @{
            foreach(TransactionDetailModel TransactionDetail in Model) {
                Html.RenderPartial("_TransactionHistoryItem", TransactionDetail);
            }
        }
      </ul>
    }
  </div>
</div>

@section Scripts {
  
  @Scripts.Render("~/bundles/transactionHistory")
  <script type="text/javascript">
     $(function() {
          $('.SearchResults li').on("click", function () {
              var transId = $(this).attr('data-id');
              window.location = '@(Url.Content("TransactionDetails"))' + '/' + transId;
          }); 
     });
  </script>
}